### ISSUE TITLE
How to deploy a Golang app into apprunner

### ISSUE THREAD

**Issue by EyckSDLuo** [danielflower/app-runner#17]
Hi Dan

May I know how to deploy a golang app into apprunner? I can't find the usage for golang deployment.

**Comment by danielflower** [comment]
Like the other languages, it will only work if golang is installed and available on the path. If it is, then the go runner defines the commands:

https://github.com/danielflower/app-runner/blob/master/src/main/java/com/danielflower/apprunner/runners/GoRunner.java#L20

Those commands are also shown on the Getting Started page on the App Runner home app.

Note that for go it will probably need to clone git repos during the build so the server needs to be able to access the internet.
