### ISSUE TITLE
Can I use wsgi server in python web apps?

### ISSUE THREAD

**Issue by JackKCWong** [danielflower/app-runner#25]
For python web apps it is usually run behind a wsgi server like gunicorn which uses child processes to serve concurrent requests.
But the python sample app seems to suggest not to use child processes in app runner. Or is this just peculiar to Flask?

>     #Set debug=False and threaded=True to prevent Flask forking a child process that doesn't get shut down

**Comment by JackKCWong** [comment]
It seems there is no way to kill a process tree in [java 8](https://stackoverflow.com/questions/10124299/how-do-i-terminate-a-process-tree-from-java), which has been fixed in java 9 with [ProcessHandle].(https://docs.oracle.com/javase/9/docs/api/java/lang/ProcessHandle.html)
Is it moving to java 9 or better anytime soon?

**Comment by danielflower** [comment]
I don't know enough about Python to answer your first question sorry. As for the second, yeah I'm considering moving to Java 11.

**Comment by JackKCWong** [comment]
thanks. java 11 sounds good. python is a bit special that even multi threading can only utilize one cpu. So production-ready web apps are usually running behind a wsgi server, which is something like the java servelet container for java web app. I will check again when we are on java 11 to see if/how apprunner should support this. :)
